# Generated by Django 5.0.2 on 2024-08-02 16:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingApp', '0003_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 2, 16, 48, 54, 638347, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
