# Generated by Django 5.0.2 on 2024-08-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBookingApp', '0003_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
    ]
