# Generated by Django 5.0.2 on 2024-08-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100)),
                ('drink_size', models.CharField(max_length=50)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('drink_amount', models.PositiveIntegerField()),
                ('drink_image', models.ImageField(blank=True, null=True, upload_to='drink_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('food_amount', models.PositiveIntegerField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
