# Generated by Django 5.0.2 on 2024-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100)),
                ('drink_size', models.CharField(max_length=50)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drink_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
