# Generated by Django 5.0.2 on 2024-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDrinksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
