# Generated by Django 5.0.2 on 2024-08-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDrinksApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodDrinksApp.drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodDrinksApp.food'),
        ),
    ]
