# Generated by Django 5.0.2 on 2024-08-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDrinksApp', '0003_drink_drink_image_food_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
