# Generated by Django 5.0.2 on 2024-08-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0002_review_teammemberreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMemberReview',
        ),
    ]
