# Generated by Django 5.0.2 on 2024-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WelcomeApp', '0004_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
